packages:
  - packages/*
  - apps/*
  - libs/*

onlyBuiltDependencies:
  - '@alicloud/openapi-core'
  - '@nestjs/core'
  - '@scarf/scarf'
  - esbuild
  - sharp
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - dotenv
    - openai
  allowedVersions:
    "@nestjs/core": "11"
    "@nestjs/common": "11"
    "@nestjs/typeorm": "11"
    "reflect-metadata": "*"